name: 'Epiphyte Create Chain'
description: 'Spin up new ethereum chain'
inputs:
  token:
    description: Epiphyte API token
    required: true
  accounts:
    descrption: Number of accounts to create
    required: false
    default: 5
  fork:
    description: specify `network` or `network@block` (e.g. `mainnet@100`)
    required: false
  id:
    description: chain id of Ethereum chain
    required: false
  mnemonic:
    description: mnemonic seed to use for account generation
    required: false
  name:
    description: used to identify chain for further api calls
    required: false
outputs:
  accounts:
    description: List of accounts and private keys
  endpoint:
    description: host name of chain
  id:
    description: chain id of Ethereum chain
  mnemonic:
    description: mnemonic seed for created wallets
  name:
    description: name of Epiphyte chain
runs:
  using: 'node16'
  main: 'index.js'