name: Epiphyte Create Chain Action Test
on: [pull_request]
jobs:
  Create-Destroy-Epiphyte-Chain:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Create test chain
        id:   testnet
        uses: ./create
        with:
          token: ${{ secrets.EPIPHYTE_TOKEN }}
          accounts: 7
          id: 42
          fork: mainnet@50000
          mnemonic: mask flat gap evidence spare cigar drama latin oppose ill helmet crush
          name: ${{ github.sha }}
      - name: Test Output
        run: | 
          cd create
          node test.js
        env: 
          ACCOUNTS: ${{ steps.testnet.outputs.accounts }}
          HOSTNAME: ${{ steps.testnet.outputs.hostname }}
          NAME: ${{ steps.testnet.outputs.name }}
          SHA: ${{ github.sha }}
          ID: ${{ steps.testnet.outputs.id }}
      - name: Destroy test chain by name
        uses: ./destroy
        with:
          token: ${{ secrets.EPIPHYTE_TOKEN }}
          name: ${{ github.sha }}