name: Epiphyte Create Chain Demo
on: [push]
jobs:
  Create-Destroy-Epiphyte-Chain:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Create test chain
        id:   testnet
        uses: ./create
        with:
          token: ${{ secrets.EPIPHYTE_TOKEN }}
      - name: Destroy test network
        uses: ./destroy
        with:
          token: ${{ secrets.EPIPHYTE_TOKEN }}
          name: ${{ steps.testnet.outputs.name }}
